
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async search(query: SearchQuery) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async status() : Promise<Result<IndexStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kicks off (or restarts) indexing for `path`. Matches the CLI's own
 * `findra index --daemon <path>` behavior of stopping and replacing any
 * daemon already running - used by the "重建索引" tray/menu action.
 */
async rebuildIndex(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_index", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkPermission() : Promise<PermissionStatus> {
    return await TAURI_INVOKE("check_permission");
},
async ensureDaemon() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_daemon") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens (or focuses) the Preferences window - the same action the tray
 * menu's "偏好设置…" triggers, exposed as a command so the in-app gear
 * button doesn't have to reimplement window lifecycle logic on the JS
 * side (see `window.rs::show_preferences`, the single place that's
 * handled).
 */
async openPreferences() : Promise<void> {
    await TAURI_INVOKE("open_preferences");
},
async getPlatform() : Promise<string> {
    return await TAURI_INVOKE("get_platform");
},
async checkProtocolVersion() : Promise<Result<VersionCompat, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_protocol_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getExcludedPaths() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_excluded_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addExcludedPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_excluded_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeExcludedPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_excluded_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restarts the daemon so a just-edited `~/.findra/config.toml` (e.g. a
 * changed excluded-directories list) takes effect - the daemon only reads
 * that file at startup. Sends `StopDaemon` and gives it a couple seconds
 * to actually exit and release its socket/database before spawning a
 * fresh one - a simplification of findra-cli's own PID-based wait-then-
 * escalate-to-SIGKILL restart logic (`stop_running_daemon` in
 * findra-cli/src/main.rs), acceptable here since a slightly slow restart
 * just delays picking up the config change rather than losing data.
 */
async restartDaemon() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_daemon") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type EntryKind = "File" | "Directory" | "Symlink"
export type FileEntry = { id: number; parent_id: number; name: string; path: string | null; size: number; mtime: number; 
/**
 * Creation time (birth time on macOS/some Linux filesystems); falls
 * back to `mtime` when the OS/filesystem doesn't expose one.
 * `#[serde(default)]` so an older daemon/client that predates this
 * field doesn't hard-fail decoding the rest of the message.
 */
ctime?: number; kind: EntryKind; volume_id: number }
export type IndexStats = { total_files: number; total_size: number; last_sync: number; providers: string[]; 
/**
 * Per configured path, whether a live watch is currently running
 * (`true`) or that path is only reflecting its last scan/watch-failure
 * state (`false`) - lets a client show "which of my paths are
 * real-time vs. periodic" instead of a single blanket health flag.
 */
watch_status?: ([string, boolean])[]; 
/**
 * The daemon's `PROTOCOL_VERSION` at build time. `#[serde(default)]`
 * so a pre-versioning daemon still deserializes cleanly - an empty
 * string is itself the signal "this daemon predates version
 * negotiation, treat it as unknown/possibly incompatible" rather than
 * a decode error.
 */
protocol_version?: string }
export type PermissionStatus = { platform: Platform; granted: boolean; 
/**
 * True once this is a real daemon-reported signal rather than the
 * pre-scan heuristic - the onboarding UI uses this to distinguish
 * "confirmed missing" from "haven't checked yet".
 */
confirmed: boolean; 
/**
 * Paths the daemon could only watch periodically rather than in real
 * time, when `confirmed` is true - lets the UI name what's degraded
 * instead of a blanket warning.
 */
degraded_paths: string[] }
export type Platform = "macos" | "windows" | "linux"
export type SearchQuery = { pattern: string; regex: boolean; case_sensitive: boolean; pinyin: boolean; extensions: string[]; min_size: number | null; max_size: number | null; path_filter: string | null; sort_by: SortField; descending: boolean; limit: number | null }
export type SortField = "Name" | "ModTime" | "CTime" | "Size" | "Path"
export type VersionCompat = { kind: "Match" } | { kind: "Unknown" } | { kind: "Mismatch"; daemon: string; app: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
